Adicionado paginação e filtros
negherbon/senai-5s-webapp pull request #49
Opened 2018-05-16 01:00 UTC by andrefelipeml

2018-05-16 02:13 UTC, guilhermenass commented on src/app/enviroments-type/enviroment-type.component.ts
> +    returnedArray: EnviromentType[];
Não gosto muito de colocar return ou returned em nomes de variáveis, métodos, etc. Não poderia ser environmentType mesmo?

2018-05-16 02:15 UTC, guilhermenass commented on src/app/enviroments-type/enviroment-type.component.ts
> +    typed = typed.toLowerCase();
Ao meu ver, não precisaria dessa linha. Ali no includes, tu pode passar includes(typed.toLowerCase()) tá ligado?

2018-05-16 02:16 UTC, guilhermenass commented on src/app/enviroments/enviroment.component.html
> +              <tr *ngFor="let enviroment of returnedArray">
Mesma coisa aqui... não poderia ser environments invés de returnedArray?

2018-05-16 02:18 UTC, guilhermenass commented on src/app/questions/question.component.ts
> +    this.returnedArray = this.questions.filter(quest => quest.title.toLowerCase().includes(typed));
Colocar question invés de quest. Quest em inglês é missão uhahuah... sei que o sentido foi abreviar, mas não dá pra usar question mesmo?

2018-05-16 02:19 UTC, guilhermenass commented on src/app/users/user.component.html
> +            <input class="form-control col-sm-10" #nameUserSearch placeholder="Pesquise por um Usuário" (keyup)="findUsers(nameUserSearch.value)" >
#userNameSearch invés de #nameUserSearch

2018-05-16 02:21 UTC, guilhermenass requested changes
@andrefelipeml alterações simples cara. Mas de resto está ótimo.

2018-05-17 12:19 UTC, andrefelipeml commented on src/app/enviroments-type/enviroment-type.component.ts
> +    returnedArray: EnviromentType[];
Ai ficaria 2 arrays com nomes iguais, e precisa de 2 arrays, 1 com todos os registros e outro com os registros que estão sendo exibidos, qual nome sugeriria ?

2018-05-17 23:39 UTC, guilhermenass approved these changes
Agora está ok, valeu maninho

2018-05-17 23:39 UTC, merged

2018-05-17 23:42 UTC, osorioJunior95 commented
Nass, ta errado ainda.
Linha 57 tem erro, olha lá

Em 17 de mai de 2018 8:39 PM, "Guilherme Nass" <notifications@github.com>
escreveu:

> *@guilhermenass* approved this pull request.
>
> Agora está ok, valeu maninho
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/negherbon/senai-5s-webapp/pull/49#pullrequestreview-121251835>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AMxGJVBYLmEbfPFQ4HGwvXUnngyDpIz6ks5tzgoygaJpZM4UAfae>
> .
>

2018-05-17 23:43 UTC, osorioJunior95 commented
Nass, outra coisa.
Veja se a rota está certa, pq está vindo notificação pro meu e-mail

Em 17 de mai de 2018 8:39 PM, "Guilherme Nass" <notifications@github.com>
escreveu:

> *@guilhermenass* approved this pull request.
>
> Agora está ok, valeu maninho
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/negherbon/senai-5s-webapp/pull/49#pullrequestreview-121251835>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AMxGJVBYLmEbfPFQ4HGwvXUnngyDpIz6ks5tzgoygaJpZM4UAfae>
> .
>